### ISSUE TITLE
DS - Maintenance & Support - Q1 2024

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#96]
# Project Status Overview

### Project Objective:

- This Epic represents ongoing work by the Design System team that is needed to maintain the Mobile Design System.  This includes:
    - keeping dev libraries up to date 
    - discovery on processes
    - updating documentation not related to other Epic work

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal dependency ? |   |
| External dependency ?  |   |
|  |   |

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

</details>

### Monthly Update for Stakeholders
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|03/24| On Track | Made Repo public
|Month Year| .....
|Month Year|
|Month Year|
</details>

# Detailed Project Scope 

### Problem Statement

The Mobile Design System lives in it's own repo and has it's own publishing process.  We rely on tool and libraries that must be maintained.  We need to account for the time to do so.  This is an ongoing Epic.

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.)
 
 2.) 
 
 3.) 
 
 
</details>

### Important Project Links 
<details>
<summary>Links</summary>
 
- Github Epic
- Github VA Mobile Page
- - Product Brief
- Product Canvas
- Design 
   - Discovery
   - Mockups
   - Final Design
   - Figma File
- Research
   - Research Plan
   - Research Results and Findings
-Analytics
-Decision Log 
</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:**  Ryan Thurlwell

**Ad Hoc:** 
- **Mobile Team**:  Design System
- **Mobile Team Lead:** Kelly Lein
- **FE Engineering:** Narin Ratana
- **Design:** Jessica Woodin

</details>

### Questions 
<details>
<summary>Open Questions</summary>
 
 - How are we measuring success? 
 
 - What is MVP and what is out of scope?
   
 - Has there been existing research or work done on this project before?
   
 - Is this work being done within the VA today (ex. web) 
 
</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer | Owner |
|--------|----------|------|
| | | |
| | | |

</details>

### Change / Decision Log 

Product will need to create on in the Github folder and link it here. 

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] PM to create new Github epic and fill out accordingly (Type - Epic, Template - Epic Ticket
       - [ ]  Updated so it is seen in Mobile and External Github Boards - may need to view this epic in Github and not Zenhub
   - [ ] PM to create new Github folder for feature or update existing
       - [ ] Create a separate document for the project's decision log - link it here  
   - [ ] Project Kickoff session to review problem statement, Veteran experience, and goals with stakeholders
   - [ ] Determine team roles, responsibilities, approvers with stakeholders
   - [ ] Determine future cadance reviews with stakeholders 
   - [ ] Review dependencies 
   - [ ] Scope finalized or approved by Mobile POs
   - [ ] PM to create and/ or link Product Brief
   - [ ] Other:
